name: Update IPTV Playlist

on:
  schedule:
    - cron: "15 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run script
        run: python aggiorna_memo_github.py --github push
